#!/bin/sh
set -e

# --- $NULL SOVEREIGN DECODER: PROFESSIONAL ENVELOPE ---
# VERSION: v3.1-PUBLIC-RECOVERY
# POLICY: DATA SOVEREIGNTY / PATH C

# 1. MAINTENANCE POLICY
# This public decoder is bit-perfect for archives generated by v3.1 cores.
# For forward-compatibility with newer engine versions, ensure you are
# using the latest SDK build.
# Warning: Non-maintained builds may not support future archive signatures.

# 2. EXECUTION SAFETY (Quiet Fail-Closed)
# Detect if the environment is unauthorized for secure conduction.
if [ -n "${LD_PRELOAD:-}" ] || [ -n "${LD_DEBUG:-}" ]; then
    echo "ERROR: Unsupported execution environment (Security Policy 13)."
    exit 13
fi

# 3. FAIL-CLOSED COMMAND WHITELIST
case "$1" in
    version)
        echo "$NULL Sovereign Decoder v3.1-Public (Stable)"
        ;;
    decompress)
        shift
        # Only allow decompressing into /data (mapped volume)
        /usr/local/bin/liquefy-decoder-public decompress "$@"
        ;;
    verify)
        shift
        /usr/local/bin/liquefy-decoder-public verify "$@"
        ;;
    *)
        echo "Usage: liquefy {version|decompress|verify}"
        echo "Policy: Execution envelope is SEALED. No shell access allowed."
        exit 1
        ;;
esac
